export default {
  images: {
    welcome: require('../../assets/images/welcome_img.jpeg'),
    welcoming: require('../../assets/images/welcoming_img.png'),
    cloud: require('../../assets/images/cloud_img.png'),
    temp_face: require('../../assets/images/temp_face_img.png'),
    dodge: require('../../assets/images/dodge_img.png'),
    cars: [
      require('../../assets/images/1.png'),
      require('../../assets/images/2.png'),
      require('../../assets/images/3.png'),
      require('../../assets/images/4.png'),
      require('../../assets/images/5.png'),
      require('../../assets/images/6.png'),
      require('../../assets/images/7.png'),
      require('../../assets/images/8.png'),
      require('../../assets/images/9.png'),
      require('../../assets/images/10.png'),
      require('../../assets/images/11.png'),
      require('../../assets/images/12.png'),
      require('../../assets/images/13.png'),
      require('../../assets/images/14.png'),
      require('../../assets/images/15.png'),
      require('../../assets/images/16.png'),
      require('../../assets/images/17.png'),
      require('../../assets/images/18.png'),
      require('../../assets/images/19.png'),
      require('../../assets/images/20.png'),
      require('../../assets/images/21.png'),
      require('../../assets/images/22.png'),
      require('../../assets/images/23.png'),
      require('../../assets/images/24.png'),
      require('../../assets/images/25.png'),
      require('../../assets/images/26.png'),
      require('../../assets/images/27.png'),
      require('../../assets/images/28.png'),
      require('../../assets/images/29.png'),
      require('../../assets/images/30.png'),
      require('../../assets/images/31.png'),
      require('../../assets/images/32.png'),
      require('../../assets/images/33.png'),
      require('../../assets/images/34.png'),
      require('../../assets/images/35.png'),
      require('../../assets/images/36.png'),
      require('../../assets/images/37.png'),
      require('../../assets/images/38.png'),
      require('../../assets/images/39.png'),
      require('../../assets/images/40.png'),
      require('../../assets/images/41.png'),
      require('../../assets/images/42.png'),
      require('../../assets/images/43.png'),
      require('../../assets/images/44.png'),
      require('../../assets/images/45.png'),
      require('../../assets/images/46.png'),
      require('../../assets/images/47.png'),
      require('../../assets/images/48.png'),
      require('../../assets/images/49.png'),
      require('../../assets/images/50.png'),
      require('../../assets/images/51.png'),
      require('../../assets/images/52.png'),
    ],
  },
  icons: {
    profile: require('../../assets/images/profile_icon.png'),
    lock: require('../../assets/images/lock_icon.png'),
    eye: require('../../assets/images/eye_icon.png'),
    eye_off: require('../../assets/images/eye_off_icon.png'),
    facebook: require('../../assets/images/facebook_icon.png'),
    google: require('../../assets/images/google_icon.png'),
    twitter: require('../../assets/images/twitter_icon.png'),
    apple: require('../../assets/images/apple_icon.png'),
    verified: require('../../assets/images/verified_icon.png'),
    my_password: require('../../assets/images/my_password_icon.png'),
    success: require('../../assets/images/success_icon.png'),
    completed: require('../../assets/images/completed_icon.png'),
    mail: require('../../assets/images/mail_icon.png'),
    send_mail: require('../../assets/images/send_mail_icon.png'),
    warning: require('../../assets/images/warning_icon.png'),
    pin: require('../../assets/images/pin_icon.png'),
    search: require('../../assets/images/search_icon.png'),
    favorite_filled: require('../../assets/images/favorite_filled_icon.png'),
    favorite_outlined: require('../../assets/images/favorite_outlined_icon.png'),
    person: require('../../assets/images/person_icon.png'),
    gear: require('../../assets/images/gear_icon.png'),
    clear: require('../../assets/images/clear_icon.png'),
    profile_light: require('../../assets/images/profile_light_icon.png'),
    profile_black: require('../../assets/images/profile_black_icon.png'),
    door: require('../../assets/images/door_icon.png'),
    fuel: require('../../assets/images/fuel_icon.png'),
    snow: require('../../assets/images/snow_icon.png'),
    speed: require('../../assets/images/speed_icon.png'),
    back: require('../../assets/images/back_icon.png'),
    star: require('../../assets/images/star_icon.png'),
    forward: require('../../assets/images/forward_icon.png'),
  },
};
