export default {
  images: {
    welcome: require('../../assets/images/welcome_img.jpeg'),
    welcoming: require('../../assets/images/welcoming_img.png'),
    cloud: require('../../assets/images/cloud_img.png'),
    temp_face: require('../../assets/images/temp_face_img.png'),
    dodge: require('../../assets/images/dodge_img.png'),
  },
  icons: {
    profile: require('../../assets/images/profile_icon.png'),
    lock: require('../../assets/images/lock_icon.png'),
    eye: require('../../assets/images/eye_icon.png'),
    eye_off: require('../../assets/images/eye_off_icon.png'),
    facebook: require('../../assets/images/facebook_icon.png'),
    google: require('../../assets/images/google_icon.png'),
    twitter: require('../../assets/images/twitter_icon.png'),
    apple: require('../../assets/images/apple_icon.png'),
    verified: require('../../assets/images/verified_icon.png'),
    my_password: require('../../assets/images/my_password_icon.png'),
    success: require('../../assets/images/success_icon.png'),
    completed: require('../../assets/images/completed_icon.png'),
    mail: require('../../assets/images/mail_icon.png'),
    send_mail: require('../../assets/images/send_mail_icon.png'),
    warning: require('../../assets/images/warning_icon.png'),
    pin: require('../../assets/images/pin_icon.png'),
    search: require('../../assets/images/search_icon.png'),
    favorite_filled: require('../../assets/images/favorite_filled_icon.png'),
    favorite_outlined: require('../../assets/images/favorite_outlined_icon.png'),
    person: require('../../assets/images/person_icon.png'),
    gear: require('../../assets/images/gear_icon.png'),
    clear: require('../../assets/images/clear_icon.png'),
    door: require('../../assets/images/door_icon.png'),
    fuel: require('../../assets/images/fuel_icon.png'),
    snow: require('../../assets/images/snow_icon.png'),
    speed: require('../../assets/images/speed_icon.png'),
    back: require('../../assets/images/back_icon.png'),
    star: require('../../assets/images/star_icon.png'),
  },
};
