import CarModel from '../../models/carModel';

const mockData: CarModel[] = [
  {
    id: 2,
    name: 'Ferrari 488 GTB',
    year: 2023,
    color: 'Red',
    price: 250000,
    model: '488 GTB',
    brand: 'Ferrari',
    image: 'ferrari-488.jpg',
    description:
      'The Ferrari 488 GTB is an Italian masterpiece, known for its style and performance.',
    fuelType: 'Gasoline',
    mileage: 15,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.9,
    reviewCount: 45,
    numberOfSeats: 2,
  },
  {
    id: 3,
    name: 'Audi R8',
    year: 2023,
    color: 'Blue',
    price: 170000,
    model: 'R8',
    brand: 'Audi',
    image: 'audi-r8.jpg',
    description:
      'The Audi R8 combines German engineering with a sporty design for an exhilarating driving experience.',
    fuelType: 'Gasoline',
    mileage: 20,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.6,
    reviewCount: 28,
    numberOfSeats: 2,
  },
  {
    id: 4,
    name: 'Chevrolet Corvette Stingray',
    year: 2023,
    color: 'Yellow',
    price: 80000,
    model: 'Corvette Stingray',
    brand: 'Chevrolet',
    image: 'chevrolet-corvette.jpg',
    description:
      'The Chevrolet Corvette Stingray offers incredible performance and a classic American sports car design.',
    fuelType: 'Gasoline',
    mileage: 22,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.5,
    reviewCount: 25,
    numberOfSeats: 2,
  },
  {
    id: 5,
    name: 'Nissan GT-R',
    year: 2023,
    color: 'Silver',
    price: 110000,
    model: 'GT-R',
    brand: 'Nissan',
    image: 'nissan-gtr.jpg',
    description:
      'The Nissan GT-R, also known as the Godzilla, is a high-performance legend with all-wheel drive and power.',
    fuelType: 'Gasoline',
    mileage: 16,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.8,
    reviewCount: 40,
    numberOfSeats: 2,
  },
  {
    id: 6,
    name: 'BMW M5 Competition',
    year: 2023,
    color: 'Black',
    price: 105000,
    model: 'M5 Competition',
    brand: 'BMW',
    image: 'bmw-m5.jpg',
    description:
      'The BMW M5 Competition combines luxury and high-performance for a thrilling driving experience.',
    fuelType: 'Gasoline',
    mileage: 19,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.7,
    reviewCount: 35,
    numberOfSeats: 5,
  },
  {
    id: 1,
    name: 'Porsche 911 GT3',
    year: 2023,
    color: 'White',
    price: 150000,
    model: '911 GT3',
    brand: 'Porsche',
    image: 'porsche-911.jpg',
    description:
      'The Porsche 911 GT3 is a high-performance sports car known for its speed and precision.',
    fuelType: 'Gasoline',
    mileage: 18,
    gearType: 'Automatic',
    isFavourite: false,
    isCompare: false,
    rating: 4.7,
    reviewCount: 32,
    numberOfSeats: 2,
  },
];

export default mockData;
